spring:
  application:
    name: raccoon-cloud-knowledge
  config:
    import: nacos:localhost:8848
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yml
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: password

server:
  port: 8082