server:
  port: 8081
  error:
    include-message: always

spring:
  application:
    name: raccoon-cloud-agent
  config:
    import: optional:nacos:localhost:8848
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yml
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2:7b
          temperature: 0.7

logging:
  level:
    com.raccoon.cloud.agent: debug
    org.springframework.ai: info
